#pragma once

#define SYSTEMCALL_COUNT 1

// Calls
#define SYSTEMCALL_EXIT     0
#define SYSTEMCALL_CLOSE    1
#define SYSTEMCALL_EXECVE   3
#define SYSTEMCALL_FORK     4
#define SYSTEMCALL_FSTAT    5
#define SYSTEMCALL_GETPID   6
#define SYSTEMCALL_ISATTY   7
#define SYSTEMCALL_KILL     8
#define SYSTEMCALL_LINK     9
#define SYSTEMCALL_LSEEK    10
#define SYSTEMCALL_OPEN     11
#define SYSTEMCALL_SBRK     12
#define SYSTEMCALL_STAT     13
#define SYSTEMCALL_TIMES    14
#define SYSTEMCALL_WAIT     15
#define SYSTEMCALL_WRITE    16